### ISSUE TITLE
Sublime Text 3

### ISSUE THREAD

**Issue by jopotts** [mikepfirrmann/openfolder#3]
On OSX with ST3 build 3012, the Open Folder option is always greyed out. Have you tried it on ST3 yet? (ie. Is it my setup that's wrong or does openfolder need a fix for the new ST version?)

**Comment by mikepfirrmann** [comment]
I have not yet updated Open Folder for ST3. Thanks for the reminder, I will try to get to this ASAP.

**Comment by jopotts** [comment]
Working perfectly. Good stuff. Thanks for the plugin!

**Comment by mikepfirrmann** [comment]
You're welcome. Thanks for testing the fix.

**Comment by royduin** [comment]
The plugin is marked as "Only works with Sublime Text 2" on the website from wbond: https://sublime.wbond.net/packages/Open%20Folder

Now it can't be installed through package control in Sublime Text 3. Please fix this.

**Comment by mikepfirrmann** [comment]
Package Control now knows that Open Folder supports Sublime Text 3 via https://github.com/wbond/package_control_channel/pull/2391

**Comment by royduin** [comment]
Nice! Thanks
