### ISSUE TITLE
do not show for files

### ISSUE THREAD

**Issue by ghost** [mikepfirrmann/openfolder#6]
When I right click over a folder in sidebar, it works fine. However, the same context item appears over files too. Kindly do not show the context item for files.

**Comment by ghost** [comment]
Why not?  I want it for files and am indifferent to whether it shows for folders.

**Comment by mikepfirrmann** [comment]
I do not intend to remove this functionality (by default, anyway). @jitin-sameer if you'd like to submit a pull request where you add a preference to disable OpenFolder for files, I'll take a look and merge it if everything is kosher.
