### ISSUE TITLE
Actually adds to tab menu, not sidebar context menu

### ISSUE THREAD

**Issue by ghost** [mikepfirrmann/openfolder#9]
When I use this plugin in Sublime Text 3 build 3065 it adds the "Reveal In Finder" item to the _tab's_ context menu not the sidebar's.  The README says sidebar which is a little confusing.

**Comment by mikepfirrmann** [comment]
That isn't OpenFolder. I'm running build 3066 and there is a "Reveal in Finder" option in the tab context menu and side bar context menu for all files. I think SublimeText is providing those, but I don't know where they hide the default `*.sublime-menu` files anymore and I don't have time to look for them at the moment.
